#!/usr/bin/env python3
"""Build the nine requested Arabic food-product dossiers."""
from __future__ import annotations
import importlib, subprocess, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT/"tools"))
import build_requested_portuguese_food_pages as template
from build_requested_spanish_food_pages import PRODUCTS as SOURCE
BASE="https://www.bespringchem.com"
AR={
"diammonium-phosphate-dap":{"name":"فوسفات ثنائي الأمونيوم الغذائي (DAP)","title":"مورد فوسفات ثنائي الأمونيوم الغذائي DAP | E342(ii)","description":"فوسفات ثنائي الأمونيوم DAP بدرجة غذائية E342(ii): المحتوى وP₂O₅ والنيتروجين ودرجة الحموضة وشهادة التحليل والتعبئة وعرض التوريد بالجملة.","summary":"فوسفات ثنائي الأمونيوم الغذائي ملح فوسفاتي قابل للذوبان في الماء، ويُقيّم في التطبيقات المسموح بها كمغذٍ للخميرة ومنظم للحموضة ومكوّن في أنظمة التخمير الكيميائي.","functions":["مصدر للنيتروجين والفوسفور في عمليات التخمير المنضبطة","تنظيم الحموضة والتأثير المنظّم","مكوّن في أنظمة الرفع المناسبة"],"applications":["تخمير الأغذية والمشروبات","المخبوزات والخلطات الجافة","إنتاج الخميرة"],"criteria":["محتوى DAP وP₂O₅ والنيتروجين","درجة الحموضة والرطوبة والمواد غير الذائبة","حدود الفلوريد والزرنيخ والرصاص وحجم الجسيمات"],"note":"يجب عدم الخلط بين الدرجة الغذائية ودرجة الأسمدة؛ ويُثبت الاستخدام الغذائي بمواصفة المصنع وإمكانية التتبع ووثائق الدفعة."},
"food-phosphate-blends":{"name":"خلطات الفوسفات الغذائي الوظيفية","title":"خلطات فوسفات غذائي حسب التطبيق | مورد بالجملة","description":"خلطات فوسفات غذائي وظيفية للحوم والأجبان والمخبوزات: التركيب ودرجة الحموضة والذوبان وشهادة التحليل والتوريد بالجملة.","summary":"تجمع خلطات الفوسفات الغذائي بين الفوسفات الأحادي أو البيروفوسفات أو متعدد الفوسفات بنسب محددة لتحقيق أداء تقني ثابت؛ ويُختار التركيب وفق المنتج والعملية وتشريعات سوق الوجهة.","functions":["ضبط درجة الحموضة والقدرة التنظيمية","إدارة احتباس الماء والقوام في الأنظمة البروتينية","التحكم في سرعة التفاعل أو تثبيت المكونات"],"applications":["منتجات اللحوم والأنظمة البروتينية","الأجبان المطبوخة ومنتجات الألبان","المخبوزات وخلطات عوامل الرفع"],"criteria":["التركيب النوعي والكمي الدقيق","الذوبان وpH وP₂O₅ وحجم الجسيمات","اختبار الأداء في الوصفة الفعلية ومتطلبات الوسم"],"note":"لا تكون خلطتان متكافئتين لمجرد احتوائهما على الفوسفات؛ فالتركيب ودرجة الحموضة وطول السلسلة تؤثر في النتيجة."},
"phosphoric-acid-85":{"name":"حمض الفوسفوريك الغذائي 85%","title":"حمض الفوسفوريك الغذائي 85% | مورد E338 بالجملة","description":"حمض الفوسفوريك الغذائي 85%، E338: التركيز والشوائب والمواصفة ونشرة بيانات السلامة والعبوة وعرض التوريد بالجملة.","summary":"حمض الفوسفوريك أو الأورثوفوسفوريك بتركيز 85% محلول مركز من H₃PO₄، ويُستخدم في التطبيقات المسموح بها كمحمّض ومنظم للحموضة ومادة أولية للفوسفات الغذائي.","functions":["التحميض وضبط pH","تكوين منحنى حموضة مناسب","مادة أولية لأملاح الفوسفات"],"applications":["المشروبات والمركزات والصلصات","تكرير السكر","إنتاج الفوسفات الغذائي"],"criteria":["التركيز الفعلي وطريقة التحليل","اللون والشفافية والمعادن والأيونات الحرجة","نوع الإنتاج ودرجة التنقية وتوافق العبوة"],"note":"مادة أكّالة؛ يجب أن تتوافق المناولة والتخزين والنقل ومعدات الوقاية مع نشرة بيانات السلامة السارية."},
"monoammonium-phosphate-map":{"name":"فوسفات أحادي الأمونيوم الغذائي (MAP)","title":"مورد فوسفات أحادي الأمونيوم الغذائي MAP | E342(i)","description":"فوسفات أحادي الأمونيوم MAP بدرجة غذائية E342(i): المحتوى وP₂O₅ والنيتروجين وpH وشهادة التحليل والتعبئة والتوريد بالجملة.","summary":"فوسفات أحادي الأمونيوم الغذائي ملح حمضي قابل للذوبان يوفّر الأمونيوم والفوسفات، ويُقيّم كمغذٍ للخميرة أو منظم للحموضة أو مكوّن في أنظمة الرفع المسموح بها.","functions":["مصدر للنيتروجين والفوسفور في التخمير","تنظيم الحموضة","مكوّن حمضي في بعض أنظمة الرفع"],"applications":["التخمير وتغذية الخميرة","المخبوزات","الخلطات الغذائية الجافة"],"criteria":["المحتوى وP₂O₅ والنيتروجين","pH والرطوبة والمواد غير الذائبة وحجم الجسيمات","الشوائب ومتطلبات سوق الوجهة"],"note":"لا يُخلط مع MAP المستخدم كسماد؛ ويجب تأكيد الدرجة والمنشأ والتتبع والمواصفة ووثائق الدفعة."},
"sodium-diacetate":{"name":"ثنائي أسيتات الصوديوم الغذائي E262(ii)","title":"ثنائي أسيتات الصوديوم E262(ii) | مورد مضاف غذائي بالجملة","description":"ثنائي أسيتات الصوديوم الغذائي E262(ii): التركيب وحمض الأسيتيك الحر وpH وشهادة التحليل وأكياس 25 كجم وعرض سعر بالجملة.","summary":"ثنائي أسيتات الصوديوم مركب من أسيتات الصوديوم وحمض الأسيتيك، ويمكن أن يعمل في الأغذية المسموح بها كمنظم للحموضة ومادة حافظة ومصدر لنكهة الخل.","functions":["تنظيم الحموضة والتأثير المنظّم","دعم أنظمة التحكم الميكروبي","إضفاء نكهة الملح والخل"],"applications":["الوجبات الخفيفة ومساحيق التتبيل","المخبوزات","اللحوم المصنعة والصلصات"],"criteria":["نسبة أسيتات الصوديوم إلى حمض الأسيتيك الحر","pH والرطوبة والرائحة والانسيابية","التحقق الميكروبي والحسي والتشريعي"],"note":"تعتمد فعالية الحفظ على pH والنشاط المائي والعملية والعبوة والعوامل الحاجزة الأخرى، ولا تثبتها الجرعة وحدها."},
"sodium-benzoate":{"name":"بنزوات الصوديوم الغذائية E211","title":"بنزوات الصوديوم E211 بالجملة | مورد مواد حافظة غذائية","description":"بنزوات الصوديوم الغذائية E211 مسحوق أو حبيبات: النقاوة وحجم الجسيمات وشهادة التحليل وأكياس 25 كجم وعرض سعر للكميات التجارية.","summary":"بنزوات الصوديوم ملح الصوديوم لحمض البنزويك، وتُستخدم أساساً في المشروبات والأغذية الحمضية؛ وتعتمد فعاليتها على pH ونظام الحفظ الكامل.","functions":["التحكم في الخمائر والعفن وبعض البكتيريا في الوسط الحمضي","دعم الثبات خلال مدة الصلاحية","بديل أكثر ذوباناً من حمض البنزويك"],"applications":["المشروبات والمركزات الحمضية","الصلصات والمخللات","مستحضرات الفاكهة"],"criteria":["النقاوة والرطوبة والحموضة أو القلوية والشوائب","المسحوق أو الحبيبات أو الشكل قليل الغبار","pH والتركيب الكامل والحد القانوني"],"note":"ليست حلاً عاماً لكل المنتجات؛ يجب التحقق من pH والحد التشريعي والعملية والعبوة والتخزين ومدة الصلاحية."},
"calcium-sorbate":{"name":"سوربات الكالسيوم E203","title":"سوربات الكالسيوم E203 | مورد للأسواق المسموح بها","description":"سوربات الكالسيوم E203 للأسواق التي تسمح به: النقاوة والوضع التنظيمي وشهادة التحليل والتعبئة وطلب عرض السعر.","summary":"سوربات الكالسيوم ملح الكالسيوم لحمض السوربيك، وقد استُخدم ضد العفن والخمائر؛ إلا أن وضعه التنظيمي يختلف بين الأسواق ويجب التحقق منه قبل الشراء أو تطوير الوصفة.","functions":["نشاط ضد العفن والخمائر في الظروف الملائمة","شكل صلب من السوربات لتطبيقات محددة","مكوّن في أنظمة حفظ مسموح بها"],"applications":["فئات الأغذية المسموح بها فقط","اختبارات مقارنة مع حمض السوربيك أو سوربات البوتاسيوم","الأسواق التي تسمح باستخدام E203"],"criteria":["الترخيص الحالي حسب السوق وفئة الغذاء","المحتوى والرطوبة والشوائب والذوبان","إثبات الفعالية والوسم ومدة الصلاحية"],"note":"أزال الاتحاد الأوروبي E203 من قائمة المضافات الغذائية المسموح بها عام 2018؛ ويجب مراجعة تشريع كل سوق وفئة غذائية قبل الاستخدام."},
"silicon-dioxide":{"name":"ثاني أكسيد السيليكون الغذائي E551","title":"ثاني أكسيد السيليكون E551 | مورد مانع تكتل غذائي","description":"ثاني أكسيد السيليكون غير المتبلور E551 بدرجة غذائية: نوع السيليكا والرطوبة وحجم الجسيمات وشهادة التحليل والتوريد بالجملة.","summary":"يُستخدم ثاني أكسيد السيليكون غير المتبلور بدرجة غذائية في المنتجات الجافة المسموح بها كمادة مانعة للتكتل ومحسّنة للانسيابية.","functions":["تقليل التكتل في المساحيق","تحسين الانسيابية أثناء الخلط والتعبئة","الامتزاز المنضبط للرطوبة أو السوائل"],"applications":["التوابل والخلطات الجافة","المشروبات الفورية والخلطات المسبقة","الأملاح والسكريات والمساحيق الممتصة للرطوبة"],"criteria":["نوع السيليكا غير المتبلورة المحدد","الفقد بالتجفيف والحرق والنقاوة","حجم الجسيمات والكثافة الظاهرية وأداء الانسياب"],"note":"الهوية والشكل الفيزيائي عاملان أساسيان؛ ولا تكفي ورقة بيانات عامة لإثبات ملاءمة المادة المحددة للاستخدام الغذائي."},
"gellan-gum":{"name":"صمغ الجيلان الغذائي E418","title":"صمغ الجيلان E418 بالجملة | عالي ومنخفض الأسيل","description":"صمغ الجيلان الغذائي E418 عالي أو منخفض الأسيل: الترطيب وقوة الهلام وشهادة التحليل وأكياس 25 كجم وعرض سعر بالجملة.","summary":"صمغ الجيلان هيدروكولويد يُنتج بالتخمير؛ ويعطي النوعان عالي ومنخفض الأسيل قواماً مختلفاً، ويعتمد الاختيار على المصفوفة والأيونات وpH والمعالجة الحرارية.","functions":["تكوين الهلام والبنية","تعليق الجسيمات والمعادن والكاكاو","التثبيت وتقليل انفصال الطور"],"applications":["المشروبات النباتية ومنتجات الألبان والمشروبات المحتوية على جسيمات","تحضيرات الفاكهة والحشوات","الحلويات والصلصات"],"criteria":["عالي الأسيل لقوام لين مرن ومنخفض الأسيل لهلام أكثر صلابة","درجة حرارة الترطيب وترتيب الإضافة","تأثير الكالسيوم وpH وقوة الهلام واللزوجة"],"note":"لا تُقارن قوة الهلام بين الموردين إلا مع توحيد الطريقة والتركيز والماء والأيونات ودرجة حرارة الاختبار."}}
STATIC={"/pt/":"/ar/","pt-BR":"ar","pt_BR":"ar_AR","Ingredientes alimentícios":"المكونات الغذائية","Início":"الرئيسية","Produtos":"المنتجات","Sobre nós":"من نحن","Serviços":"الخدمات","Notícias":"الأخبار","Contato":"اتصل بنا","Navegação principal":"التنقل الرئيسي","Abrir menu de navegação":"فتح قائمة التنقل","Navegação estrutural":"مسار التنقل","Ingrediente grau alimentício":"مكوّن بدرجة غذائية","Fornecimento B2B de ingredientes alimentícios":"توريد مكونات غذائية للشركات","Exportação internacional":"توريد دولي","O que é e como especificar":"هوية المنتج وكيفية تحديد المواصفة","Principais funções":"الوظائف الرئيسية","Aplicações a serem avaliadas":"تطبيقات تتطلب التقييم","Critérios de seleção para compras B2B":"معايير الاختيار للمشتريات التجارية","Documentação, embalagem e logística":"الوثائق والتعبئة والخدمات اللوجستية","Referência técnica independente":"مرجع تقني مستقل","Perguntas frequentes":"الأسئلة الشائعة","Quais dados devo enviar para solicitar uma cotação?":"ما البيانات المطلوبة للحصول على عرض سعر؟","Como confirmar que o material é grau alimentício?":"كيف يتم تأكيد الدرجة الغذائية؟","O produto pode ser usado em qualquer alimento ou país?":"هل يمكن استخدام المنتج في أي غذاء أو سوق؟","Solicitar especificação e cotação":"طلب المواصفة وعرض السعر","Enviar requisitos":"إرسال المتطلبات","Ver ingredientes alimentícios":"عرض المكونات الغذائية","Identificação":"بيانات التعريف","Links rápidos":"روابط سريعة","Solicitar informações":"إرسال استفسار","Todos os direitos reservados.":"جميع الحقوق محفوظة."}
PARA={"Para compras industriais, o nome comercial não é suficiente. Solicite a especificação vigente da origem proposta, os métodos analíticos, um COA representativo e o certificado do lote. A conformidade deve ser avaliada para a aplicação, a norma acordada e o país onde o alimento será comercializado.":"لا يكفي الاسم التجاري للمشتريات الصناعية. اطلب مواصفة المصنع الحالية وطرق التحليل ونموذج شهادة تحليل وشهادة الدفعة، وقيّم المطابقة للتطبيق والمواصفة المتفق عليها وسوق بيع الغذاء.","As aplicações são orientativas, não autorizações gerais nem recomendações de dosagem. Confirme adequação técnica, limite de uso e rotulagem no produto final.":"التطبيقات إرشادية وليست تصريحاً عاماً أو توصية بجرعة. يجب التحقق من الملاءمة التقنية وحد الاستخدام والوسم في المنتج النهائي.","Para homologação do fornecedor, solicite especificação assinada, ficha técnica, FISPQ, modelo de COA, declarações regulatórias e certificados aplicáveis ao produto, à fábrica e ao período de fornecimento. Confirme peso líquido, material da embalagem e do revestimento interno, paletização, marcações, prazo de validade, armazenagem, porto de destino e Incoterm.":"لتأهيل المورد، اطلب المواصفة الموقعة وTDS وSDS ونموذج COA والإقرارات التنظيمية والشهادات السارية. أكّد الوزن الصافي ومادة العبوة والبطانة والمنصات والوسم والصلاحية والتخزين والوجهة وشروط Incoterms.","Informe produto, grau, limites críticos, quantidade, embalagem e destino.":"اذكر المنتج والدرجة والحدود الحرجة والكمية والتعبئة والوجهة."}
PARA.update({
 "Consulte a ":"راجع ",
 "referência técnica oficial indicada para este produto":"المرجع الفني الرسمي المحدد لهذا المنتج",
 " como apoio à identidade e ao contexto regulatório. A especificação contratual e a legislação vigente do mercado de destino prevalecem em cada operação.":" للتحقق من الهوية والسياق التنظيمي. وتظل المواصفة التعاقدية والأنظمة السارية في سوق الوجهة هي المرجع الملزم.",
 "Informe aplicação, norma e limites críticos, volume anual e por embarque, embalagem, destino, Incoterm, certificados e data necessária. Isso permite comparar propostas tecnicamente equivalentes.":"اذكر التطبيق والمواصفة والحدود الحرجة والحجم السنوي وحجم الشحنة والتعبئة والوجهة وشروط Incoterms والشهادات والموعد المطلوب، حتى يمكن إعداد عروض قابلة للمقارنة فنياً.",
 "Verifique a especificação da origem exata, a documentação do sistema de qualidade, as declarações aplicáveis e o COA do lote. O nome do produto, isoladamente, não comprova o grau.":"تحقق من مواصفة المصنع المحدد ووثائق نظام الجودة والإقرارات ذات الصلة وشهادة تحليل الدفعة؛ فالاسم وحده لا يثبت الدرجة الغذائية.",
 "Não. Confirme categoria de alimento, função, limite de uso e rotulagem na legislação vigente do mercado de destino.":"لا. يجب التحقق من فئة الغذاء والوظيفة وحد الاستخدام ومتطلبات الوسم وفق الأنظمة السارية في سوق الوجهة.",
 "Fornecedor de ingredientes alimentícios, aditivos para nutrição animal e produtos químicos industriais.":"مورد للمكونات الغذائية وإضافات تغذية الحيوان والمواد الكيميائية الصناعية.",
})
def page(slug,p,src):
 raw=template.page(slug,p,src).replace('<html lang="pt-BR">','<html lang="ar" dir="rtl">')
 for d in (STATIC,PARA):
  for a,b in d.items(): raw=raw.replace(a,b)
 return raw
def add(slug):
 path=ROOT/"products/food-ingredients"/f"{slug}.html"; rel=path.relative_to(ROOT).as_posix(); raw=subprocess.run(["git","show",f"HEAD:{rel}"],cwd=ROOT,check=True,stdout=subprocess.PIPE).stdout.decode(); cur=path.read_text(encoding="utf-8")
 for code,folder in (("es","es"),("pt-BR","pt"),("ru","ru"),("de","de")):
  u=f"{BASE}/{folder}/products/food-ingredients/{slug}.html"
  if f'hreflang="{code}" href="{u}"' in cur and f'hreflang="{code}"' not in raw: raw=raw.replace('<link rel="alternate" hreflang="x-default"',f'<link rel="alternate" hreflang="{code}" href="{u}"><link rel="alternate" hreflang="x-default"',1)
 u=f"{BASE}/ar/products/food-ingredients/{slug}.html"; raw=raw.replace('<link rel="alternate" hreflang="x-default"',f'<link rel="alternate" hreflang="ar" href="{u}"><link rel="alternate" hreflang="x-default"',1); path.write_text(raw,encoding="utf-8")
def main():
 out=ROOT/"ar/products/food-ingredients"; out.mkdir(parents=True,exist_ok=True)
 for s,p in AR.items(): (out/f"{s}.html").write_text(page(s,p,SOURCE[s]),encoding="utf-8"); add(s)
 importlib.import_module("build_industry_application_pages").rebuild_sitemap(); print("Built 9 Arabic pages")
if __name__=="__main__": main()
