"""Build the 34 English industry-application pages and wire their six parent hubs."""

from __future__ import annotations

import html
import json
import re
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://www.bespringchem.com"
DATE = "2026-07-18"


def page(slug, title, focus, keyword, products, metrics, faq):
    return dict(slug=slug, title=title, focus=focus, keyword=keyword,
                products=products, metrics=metrics, faq=faq)


GROUPS = [
    dict(
        hub="food-industry-solutions.html", hub_title="Food Industry Solutions",
        catalog="../products/food-ingredients.html", image="food-ingredients-og.jpg",
        card_class="bsfi-application", grid_class="bsfi-application-grid",
        source=("FDA: Types of Food Ingredients", "https://www.fda.gov/food/food-additives-and-gras-ingredients-information-consumers/types-food-ingredients"),
        variables=["finished-food target and current defect", "formula pH, water, salt, fat and protein", "mixing, holding, heating, cooling and storage", "permitted use and labeling in the destination market"],
        pages=[
            page("meat-poultry-phosphate-systems", "Meat & Poultry Ingredient Solutions", "improve moisture retention, cooked yield, texture, emulsion stability, color and shelf-life control in processed meat and poultry", "meat processing ingredients", ["STPP", "TSPP", "TKPP", "SHMP", "Phosphate blends", "Sodium lactate", "Potassium lactate", "Sodium erythorbate", "EDTA", "Carrageenan", "CMC", "Soy and pea proteins"], ["brine pickup and equalization", "purge and cook loss", "texture, color and sensory shelf life"], ("Which ingredients are commonly screened for processed meat and poultry?", "Phosphate systems, lactates, antioxidants, hydrocolloids and functional proteins may address different parts of the process. The correct system depends on the meat, formula, equipment, market and measured failure.")),
            page("seafood-phosphate-selection", "Seafood Processing Ingredient Solutions", "manage water binding, freeze-thaw loss, oxidation, color and coating stability in shrimp, fish and shellfish", "seafood processing ingredients", ["STPP", "TKPP", "SHMP", "Phosphate blends", "Sodium citrate", "Citric acid", "EDTA", "Sodium erythorbate", "CMC", "Carrageenan", "Sodium alginate", "Xanthan gum"], ["net uptake after drainage", "thaw and cook loss", "texture, appearance and retained phosphate"], ("Is phosphate the only ingredient group used in seafood processing?", "No. Phosphates may support water binding and sequestration, while citrates, antioxidants and hydrocolloids can address water chemistry, oxidation, glaze or coating behavior.")),
            page("bakery-leavening-phosphate-solutions", "Bakery Ingredient & Formulation Solutions", "control leavening timing, dough handling, crumb texture, fortification and microbial shelf life in bakery products", "bakery ingredient solutions", ["SALP", "SAPP", "MCP", "Sodium bicarbonate", "Calcium propionate", "Potassium sorbate", "DATEM", "DMG", "CMC", "Xanthan gum", "Guar gum", "Citrus fiber", "DCP and TCP"], ["batter or dough pH", "volume, spread and crumb structure", "mold-free shelf life and sensory quality"], ("How should bakery ingredients be selected?", "Match leavening acids, preservatives, emulsifiers, hydrocolloids and mineral sources to the specific bakery format, process time, pH, water activity and finished-product target.")),
            page("dairy-cheese-ingredient-solutions", "Dairy & Cheese Ingredient Solutions", "improve processed-cheese emulsification, melt, dairy texture, mineral balance, suspension and consistency", "dairy ingredient solutions", ["DSP", "DKP", "TKP", "TSPP", "Sodium citrate", "Potassium citrate", "Calcium chloride", "Carrageenan", "CMC", "Gellan gum", "Pectin", "MDG", "Polysorbates", "Whey and dairy proteins"], ["pH and mineral balance", "melt, oil separation and firmness", "viscosity, syneresis and shelf stability"], ("Which ingredients are used as dairy stabilizers or cheese emulsifying salts?", "Citrate and phosphate salts may manage pH, calcium and protein emulsification, while carrageenan, CMC, gellan and pectin may support body, suspension and water control in suitable dairy systems.")),
            page("beverage-formulation-ingredient-solutions", "Beverage Formulation Ingredient Solutions", "fine-tune acidity, sweetness, mouthfeel, protein or particle suspension and storage stability in beverage systems", "beverage formulation ingredients", ["Citric acid", "Lactic acid", "Phosphoric acid", "Sodium citrate", "Potassium citrate", "Gum arabic", "CMC", "Gellan gum", "Pectin", "Maltodextrin", "Erythritol", "Sorbitol", "Dairy and plant proteins"], ["pH, titratable acidity and Brix", "sedimentation and ring formation", "viscosity, flavor and accelerated stability"], ("What causes beverage instability?", "Acid-protein interaction, minerals, particle size, poor hydration, heat treatment and storage temperature may all contribute. Select acids, buffers, gums and carriers only after identifying the mechanism.")),
            page("prepared-food-sauce-filling-solutions", "Prepared Food, Sauce & Filling Ingredient Solutions", "build stable sauces, fillings, dressings and convenience foods with controlled viscosity, emulsion, freeze-thaw behavior and shelf life", "prepared food ingredient solutions", ["CMC", "Xanthan gum", "Guar gum", "Carrageenan", "Pectin", "Sodium alginate", "Acetylated distarch phosphate", "MDG", "Polysorbates", "Pea and soy proteins", "Maltodextrin", "Potassium sorbate", "Sodium benzoate", "Sodium diacetate"], ["hot and cold viscosity", "emulsion and freeze-thaw stability", "pH, water activity and sensory shelf life"], ("Which stabilizer is best for sauces and fillings?", "There is no universal stabilizer. Shear, heating, pH, salt, fat, protein and freeze-thaw exposure determine whether a starch, gum, emulsifier, protein or combination should be tested.")),
        ]),
    dict(
        hub="animal-nutrition-solutions.html", hub_title="Animal Nutrition Solutions",
        catalog="../products/animal-nutrition.html", image="feedadditives-og.jpg",
        card_class="bsan-application", grid_class="bsan-application-grid",
        source=("Feed phosphates in poultry and swine nutrition", "https://pmc.ncbi.nlm.nih.gov/articles/PMC9834723/"),
        variables=["animal species, production phase and nutrient target", "basal diet, digestibility matrix and native nutrient contribution", "powder, granule or liquid form and feed-mill process", "feed authorization, impurity limits and nutritionist approval"],
        pages=[
            page("poultry-feed-phosphate-qualification", "Poultry Feed Ingredient Solutions", "supply amino acids, phosphorus, calcium, buffers, trace minerals and functional nutrients for broiler, layer and breeder feeds", "poultry feed ingredients", ["DL-Methionine", "L-Lysine", "L-Threonine", "L-Valine", "MCP", "DCP", "Sodium bicarbonate", "Salt", "Copper, zinc and manganese sources", "Choline chloride", "Betaine", "Citric and fumaric acids"], ["analyzed nutrient contribution", "documented digestibility basis", "mix uniformity, pellet quality and bird-stage fit"], ("Should poultry ingredients be selected only by assay?", "No. Nutrient form, digestibility, impurities, physical quality, phytase matrix, feed process and the broiler or layer phase must be reviewed together.")),
            page("swine-feed-phosphate-selection", "Swine Feed Ingredient Solutions", "provide digestible amino acids, calcium and phosphorus sources, acidifiers and trace nutrients for nursery, grower and sow diets", "swine feed ingredients", ["L-Lysine", "L-Threonine", "L-Valine", "DL-Methionine", "MCP", "DCP", "Citric acid", "Fumaric acid", "Copper, zinc and manganese sources", "Choline chloride", "Betaine", "Glycerin"], ["standardized digestible nutrient contribution", "acid-binding capacity and palatability", "flow, segregation and feed conversion trial endpoints"], ("How do MCP and DCP fit into swine feed?", "They supply calcium and phosphorus, but practical value depends on digestible phosphorus, calcium balance, source consistency, fluorine, contaminants and delivered cost—not total phosphorus alone.")),
            page("ruminant-mineral-premix-phosphate-systems", "Ruminant Feed Ingredient Solutions", "build mineral, buffer and functional-nutrient programs for dairy cattle, beef cattle and other ruminants", "ruminant feed ingredients", ["MCP", "DCP", "Sodium bicarbonate", "Salt", "Magnesium derivatives", "Copper, zinc and manganese sources", "Betaine", "Choline chloride", "Glycerin", "Mono propylene glycol"], ["forage and water mineral analysis", "intake, ration balance and production stage", "premix flow, caking and storage stability"], ("Can one mineral premix fit every ruminant ration?", "No. Forage, water, dry-matter intake, production stage and local limits change the mineral and buffer gap. A qualified ruminant nutritionist should approve the formula.")),
            page("aquaculture-feed-ingredient-solutions", "Aquaculture Feed Ingredient Solutions", "support amino-acid balance, mineral nutrition, feed stability and functional nutrient targets in fish and shrimp feeds", "aquaculture feed ingredients", ["DL-Methionine", "L-Lysine", "L-Threonine", "L-Valine", "MCP", "DCP", "Copper, zinc and manganese sources", "Betaine", "Choline chloride", "Citric acid", "Ascorbic acid", "Potassium sorbate"], ["species- and life-stage nutrient specification", "water stability and nutrient leaching", "pellet durability, intake and controlled feeding results"], ("What should be checked when sourcing aquaculture feed minerals?", "Confirm nutrient assay and availability, fluorine and heavy-metal limits, particle size, water stability, destination-market authorization and the complete feed formulation.")),
            page("feed-premix-flow-trace-mineral-compatibility", "Premix & Compound Feed Ingredient Solutions", "control nutrient delivery, segregation, caking and reactive contacts in premixes, concentrates and complete feeds", "feed premix ingredients", ["DL-Methionine", "L-Lysine", "L-Threonine", "L-Valine", "MCP", "DCP", "Copper, zinc, manganese and magnesium sources", "Choline chloride", "Betaine", "Glycerin", "Mono propylene glycol", "Citric and fumaric acids"], ["particle-size and density distribution", "coefficient of variation after mixing", "flow, caking and nutrient retention"], ("Why does ingredient compatibility matter in feed premixes?", "Concentrated minerals, vitamins, acids and hygroscopic nutrients may react or segregate. Particle engineering, carriers, packaging and storage time must be evaluated with the actual premix.")),
        ]),
    dict(
        hub="industrial-cleaning-solutions.html", hub_title="Industrial Cleaning Solutions",
        catalog="../products/home-care-industrial-cleaning.html", image="homecareindustrialcleaning-og.jpg",
        card_class="bsfi-application", grid_class="bsfi-application-grid",
        source=("EPA Safer Choice: Functional Classes", "https://www.epa.gov/saferchoice/functional-classes"),
        variables=["soil type, loading and required removal", "substrate, seals and equipment compatibility", "water hardness, temperature, contact time and mechanical action", "worker safety, transport classification and local product rules"],
        pages=[
            page("laundry-detergent-ingredient-solutions", "Laundry Detergent Ingredient Solutions", "balance surfactancy, builders, alkalinity, oxygen bleaching and powder or liquid processing", "laundry detergent raw materials", ["LABSA", "SLES", "Soda ash", "Sodium silicate", "Sodium sulphate", "Sodium percarbonate", "Sodium bicarbonate", "Hydrogen peroxide", "Citric acid", "CMC"], ["detergency across target stains", "hard-water tolerance and redeposition", "powder flow or liquid stability"], ("What are the main raw-material groups in laundry detergent?", "Surfactants remove and disperse soil; builders and alkalis manage water and pH; bleaching agents address oxidizable stains; salts, polymers and carriers support processing and product form.")),
            page("hard-surface-cleaner-ingredient-solutions", "Hard-Surface Cleaner Ingredient Solutions", "combine wetting, soil removal, solvent action and controlled pH for floors, kitchens, bathrooms and general surfaces", "hard surface cleaner ingredients", ["SLES", "LABSA", "Alcohols", "Mono propylene glycol", "Benzalkonium chloride", "Citric acid", "Lactic acid", "Gluconic acid", "Soda ash", "Sodium bicarbonate"], ["soil removal and streaking", "surface compatibility", "clarity, pH and storage stability"], ("Can one hard-surface cleaner be used on every material?", "No. Stone, aluminum, coatings, wood and other substrates tolerate different pH, solvents and contact times. Compatibility testing is required.")),
            page("industrial-degreaser-formulation-ingredients", "Industrial Degreaser Formulation Ingredients", "remove oily workshop and plant soils through coordinated solvent, surfactant and alkaline action", "industrial degreaser ingredients", ["Alcohols", "Mono propylene glycol", "LABSA", "SLES", "Caustic soda", "Caustic potash", "Sodium silicate", "Soda ash", "Citric acid"], ["oil removal under defined contact time", "emulsion or rinse behavior", "corrosion, residue and operator safety"], ("Should an industrial degreaser always be strongly alkaline?", "No. Soil, substrate and cleaning method determine whether solvent, neutral surfactant, alkaline or emulsion-cleaner chemistry is appropriate.")),
            page("acid-cleaner-descaler-ingredient-solutions", "Acid Cleaner & Descaler Ingredient Solutions", "remove compatible mineral scale, rust-related deposits and inorganic soils with controlled acid systems", "descaling chemicals", ["Citric acid", "Gluconic acid", "Hydrochloric acid", "Lactic acid", "Phosphoric acid", "SLES", "Alcohols"], ["scale dissolution rate", "base-metal and seal compatibility", "spent-bath pH and rinse condition"], ("Which acid is best for descaling?", "The deposit, metallurgy, concentration, temperature, inhibitor package and discharge route determine the choice. Bench compatibility testing is essential.")),
            page("institutional-cleaning-hygiene-ingredients", "Institutional Cleaning & Hygiene Ingredients", "support commercial cleaning programs with surfactant, solvent, oxidizing and suitable antimicrobial ingredient options", "institutional cleaning chemicals", ["Benzalkonium chloride", "SLES", "Alcohols", "Hydrogen peroxide", "SDIC", "TCCA", "Sodium hypochlorite", "Peracetic acid", "Citric acid", "Sodium bicarbonate"], ["cleaning result before hygiene treatment", "active concentration and contact time", "surface compatibility and permitted claims"], ("Does an antimicrobial raw material make a finished product a disinfectant?", "No. The finished formulation, active level, efficacy testing, label and local registration determine whether any disinfectant claim is permitted.")),
            page("industrial-plant-cleaning-chemical-systems", "Industrial Plant Cleaning Chemical Systems", "select high-alkaline, acidic, oxidative or surfactant systems around plant soil, metallurgy and operating constraints", "industrial plant cleaning chemicals", ["Caustic soda", "Caustic potash", "Hydrochloric acid", "Phosphoric acid", "Citric acid", "Sodium silicate", "Hydrogen peroxide", "Sodium percarbonate", "LABSA", "SLES"], ["deposit removal and cleaning time", "metallurgy, gasket and coating compatibility", "rinse endpoint, waste load and safe handling"], ("What information is needed before selecting plant-cleaning chemicals?", "Provide the deposit, equipment material, temperature, circulation or spray method, contact time, discharge route, cleaning endpoint and worker-safety requirements.")),
        ]),
    dict(
        hub="water-treatment-solutions.html", hub_title="Water Treatment Solutions",
        catalog="../products/water-treatment.html", image="water-treatment1.jpg",
        card_class="bsfi-application", grid_class="bsfi-application-grid",
        source=("US EPA: Industrial Wastewater", "https://www.epa.gov/npdes/industrial-wastewater"),
        variables=["complete source-water or system analysis", "flow, pH, alkalinity, temperature and contaminant load", "mixing, contact, separation and monitoring equipment", "materials, discharge, potable-contact and local regulatory constraints"],
        pages=[
            page("raw-water-clarification-coagulant-solutions", "Raw-Water Clarification Coagulant Solutions", "remove turbidity, suspended solids and selected colloids before filtration or downstream treatment", "raw water treatment chemicals", ["Polyaluminum chloride", "Alum", "Aluminum sulfate", "Ferric chloride", "Ferric sulfate", "ACH", "Polyamine", "DADMAC", "Sodium aluminate", "Inorganic/organic blends"], ["settled and filtered turbidity", "dose and pH operating window", "floc settling and sludge production"], ("How is a raw-water coagulant selected?", "Use representative jar tests across seasonal water conditions, comparing removal, treated pH, residual metal, floc behavior, sludge and total operating cost.")),
            page("industrial-wastewater-coagulant-selection", "Industrial Wastewater Treatment Chemical Solutions", "optimize solids, oil, color, phosphorus and sludge separation with inorganic, organic or blended coagulants", "industrial wastewater treatment chemicals", ["Polyaluminum chloride", "Alum", "Ferric chloride", "Ferric sulfate", "ACH", "Polyamine", "DADMAC", "Organic coagulants", "Sodium aluminate", "Coagulant blends"], ["TSS, turbidity, oil or target removal", "treated pH and residual metal", "sludge volume, dewaterability and cost"], ("Can a wastewater coagulant be selected from COD alone?", "No. Industry source, particulate versus soluble COD, pH, alkalinity, oils, surfactants, metals and the separation equipment all affect selection.")),
            page("cooling-water-biofouling-control-chemicals", "Cooling-Water Biofouling Control Chemicals", "manage microbial and algae pressure in suitable cooling-water systems around demand, metallurgy and discharge constraints", "cooling water treatment chemicals", ["Sodium hypochlorite", "Calcium hypochlorite", "Chlorine", "QACs", "Sodium bromide", "Peracetic acid", "Copper sulfate"], ["oxidant demand or active residual", "microbial trend and biofilm indicators", "corrosion, discharge and system compatibility"], ("Which biocide is best for a cooling tower?", "There is no universal choice. Organism, demand, pH, metallurgy, retention time, blowdown and local discharge rules determine the treatment program.")),
            page("industrial-water-intake-biofouling-control", "Industrial Water-Intake Biofouling Control", "address algae, slime and mussel-related fouling in suitable water intakes and industrial circuits", "water intake biofouling control", ["Sodium hypochlorite", "Calcium hypochlorite", "Chlorine", "Copper sulfate", "QACs", "Sodium bromide", "Peracetic acid"], ["target-organism monitoring", "active demand and contact-time profile", "intake performance, materials and discharge compliance"], ("Can an intake-treatment program be copied from another site?", "No. Source biology, temperature, flow, demand, materials and environmental permits are site-specific and require qualified design.")),
            page("boiler-condensate-neutralizing-amine-solutions", "Boiler & Condensate Neutralizing Amine Solutions", "manage condensate pH distribution and corrosion-control programs across steam and return systems", "boiler water neutralizing amines", ["Cyclohexylamine", "Diethanolamine", "DEAE", "DMPA", "MOPA", "Monoethanolamine", "Morpholine", "Octadecylamine"], ["condensate pH by return location", "iron and copper corrosion indicators", "amine distribution, return rate and carryover"], ("How are neutralizing amines selected for steam systems?", "Selection considers volatility and distribution, operating pressure, condensate return geometry, metallurgy, feedwater chemistry, monitoring and applicable contact limits.")),
            page("process-water-reuse-chemical-solutions", "Process Water & Reuse Chemical Solutions", "condition industrial water for a defined downstream process or reuse target using staged clarification and hygiene chemistry", "process water treatment chemicals", ["Polyaluminum chloride", "ACH", "Alum", "Ferric chloride", "Polyamine", "DADMAC", "Coagulant blends", "Sodium hypochlorite", "Peracetic acid", "Sodium bromide"], ["fit-for-purpose water-quality target", "clarification and filtration performance", "microbial control, residuals and reuse stability"], ("What does fit-for-purpose water reuse mean?", "The treated-water specification is set by the next use. Chemistry and monitoring should be designed around that process rather than a single universal reuse standard.")),
        ]),
    dict(
        hub="mining-solutions.html", hub_title="Mining Solutions",
        catalog="../products/mining.html", image="mining-og.jpg",
        card_class="bsmn-stage", grid_class="bsmn-stage-grid",
        source=("US EPA: Mining Sector", "https://www.epa.gov/eg/mineral-mining-and-processing-effluent-guidelines"),
        variables=["commodity, ore mineralogy and process stage", "pulp or water chemistry, pH, redox and temperature", "residence time, solids, reagent addition and equipment", "recovery, concentrate quality, water and tailings objectives"],
        pages=[
            page("mine-water-treatment-chemical-solutions", "Mine-Water Treatment Chemical Solutions", "support clarification, precipitation, pH control, settling and process-water conditioning at mine sites", "mine water treatment chemicals", ["Polyaluminum chloride", "Aluminum sulfate", "Ferric chloride", "Flocculants", "Quick lime and hydrated lime", "Soda ash", "Caustic soda", "SHMP", "Sodium metabisulfite", "Sulfuric acid"], ["TSS, turbidity and target metals", "treated pH and precipitation window", "settling, sludge and water-reuse performance"], ("What data are needed to select mine-water chemicals?", "Provide mineral and dissolved-metal analysis, pH, alkalinity or acidity, flow variation, suspended solids, treatment target, sludge route and reuse or discharge requirements.")),
            page("mineral-leaching-chemical-solutions", "Mineral Leaching Chemical Solutions", "control acidity, alkalinity and redox conditions for the selected hydrometallurgical extraction route", "mining leaching chemicals", ["Caustic soda", "Hydrochloric acid", "Sulfuric acid", "Hydrogen peroxide", "Copper sulfate", "Lead nitrate", "Quick lime", "Soda ash", "Sodium metabisulfite", "Zinc powder", "Thiocyanate"], ["extraction and reagent consumption", "solution pH and redox profile", "impurities and downstream solution quality"], ("Can a leaching reagent be recommended from the commodity name alone?", "No. Mineralogy, liberation, oxidation state, gangue demand, temperature and downstream recovery route determine the reagent system.")),
            page("mineral-flotation-reagent-solutions", "Mineral Flotation Reagent Solutions", "screen collectors, frothers, depressants, activators and modifiers for selective mineral separation", "flotation reagents", ["Xanthates (PAX, SIPX, SIBX)", "Dithiophosphate", "MIBC", "Glycols", "CMC", "Sodium hydrosulfide", "Sodium sulfide", "Sodium metabisulfite", "Thiocarbamate", "Copper sulfate"], ["recovery and concentrate grade", "froth stability and mass pull", "selectivity, water recycle and reagent consumption"], ("How should flotation reagents be qualified?", "Use mineralogical analysis and controlled batch tests, then locked-cycle or pilot work where appropriate. Grade and recovery must be evaluated together.")),
            page("smelting-electrowinning-chemical-inputs", "Smelting & Electrowinning Chemical Inputs", "qualify suitable salts, acids and conditioning inputs for thermal and electrolytic metallurgical routes", "electrowinning chemicals", ["Copper sulfate", "Lead oxide", "Soda ash", "Sodium nitrate", "Sulfamic acid", "Sulfuric acid", "Calcium chloride"], ["chemical purity and critical impurities", "bath or slag chemistry", "current efficiency, deposit quality and materials compatibility"], ("What should an electrowinning chemical specification include?", "Define assay, insolubles and process-critical metallic or ionic impurities, physical form, packaging, transport status and the exact circuit application.")),
            page("mineral-refining-processing-chemicals", "Mineral Refining & Processing Chemicals", "manage pH, salts, dispersion and process fluids in suitable downstream mineral and metallurgical operations", "mineral processing chemicals", ["Calcium chloride", "Glycols", "Potassium carbonate", "Potassium hydroxide", "Soda ash", "Sodium bicarbonate", "SHMP", "Sodium metabisulfite", "Sodium silicate", "Sodium sulfate", "Solvents"], ["process-fluid chemistry", "product purity and impurity control", "consumption, recycle and downstream quality"], ("Why must refining chemicals be application-specific?", "The same chemical can play different roles in pH, precipitation, dispersion or fluid control. Circuit chemistry and impurity limits define the acceptable grade.")),
        ]),
    dict(
        hub="agriculture-solutions.html", hub_title="Agriculture Solutions",
        catalog="../products/agricultural-fertilizers.html", image="agriculture-fertilizers-og.jpg",
        card_class="bsfi-application", grid_class="bsfi-application-grid",
        source=("FAO: Fertilizer Use by Crop", "https://www.fao.org/4/a0443e/a0443e.pdf"),
        variables=["crop, growth stage and nutrient target", "soil, substrate and irrigation-water chemistry", "application method, concentration and stock-tank design", "fertilizer grade, registration and local agronomic approval"],
        pages=[
            page("fertigation-phosphate-fertilizer-selection", "Fertigation Phosphate Fertilizer Solutions", "select soluble phosphorus, potassium and nitrogen sources around crop demand and irrigation-water compatibility", "fertigation fertilizer", ["MKP", "MAP", "DKP", "DAP", "TKPP"], ["stock and diluted-solution clarity", "pH, EC and injector uniformity", "crop-stage nutrient delivery"], ("Which phosphate fertilizer is best for fertigation?", "MKP, MAP, DKP and DAP contribute different N-P-K ratios and solution behavior. Water chemistry, stock concentration, crop stage and the remaining nutrient program determine the fit.")),
            page("foliar-phosphorus-potassium-solutions", "Foliar Phosphorus & Potassium Solutions", "screen soluble phosphate sources for foliar nutrient programs around spray water, crop sensitivity and weather", "foliar phosphorus fertilizer", ["MKP", "DKP", "TKPP", "MAP", "Citric acid"], ["tank clarity and spray pH", "controlled leaf-safety strip", "coverage and crop response"], ("Does complete solubility guarantee foliar safety?", "No. Concentration, pH, salt load, crop stage, temperature, humidity and tank partners affect leaf safety. Begin with a controlled strip test.")),
            page("water-soluble-fertilizer-raw-material-qualification", "Water-Soluble Fertilizer Blend Ingredients", "qualify phosphorus, potassium and nitrogen raw materials for soluble NPK and specialty fertilizer blends", "water soluble fertilizer raw materials", ["MKP", "MAP", "DKP", "DAP", "TKPP"], ["nutrient assay and blend calculation", "water insolubles and dissolution", "moisture, caking and finished-blend stability"], ("What should be specified for a water-soluble fertilizer raw material?", "State chemical identity, nutrient analysis, moisture, water insolubles, chloride, heavy metals, particle size, solution pH, packing and intended market.")),
            page("greenhouse-fertilizer-stock-tank-compatibility", "Soilless Cultivation Nutrient Solutions", "choose and separate soluble nutrient sources for greenhouse, hydroponic and substrate systems", "hydroponic fertilizer ingredients", ["MKP", "MAP", "DKP", "DAP", "TKPP"], ["source-water analysis", "concentrated stock compatibility", "root-zone pH, EC and delivery uniformity"], ("Why are separate fertilizer stock tanks used in soilless cultivation?", "Concentrated phosphates can precipitate with calcium or magnesium. A/B tank design, water analysis, concentration and injection sequence help manage compatibility.")),
            page("compound-fertilizer-phosphate-raw-materials", "Compound Fertilizer Phosphate Raw Materials", "select phosphate inputs around guaranteed analysis, granulation or blending route and finished-product format", "compound fertilizer raw materials", ["MAP", "DAP", "MKP", "DKP", "TKPP"], ["nutrient balance and assay", "granulation or blend compatibility", "moisture, caking and finished-product strength"], ("How do MAP and DAP differ as compound-fertilizer inputs?", "They provide different nitrogen-to-phosphorus ratios and process behavior. The target analysis, production route, moisture, particle size and local registration determine selection.")),
            page("specialty-crop-fertilizer-programs", "Specialty Crop Fertilizer Programs", "match soluble phosphate sources to horticulture, greenhouse and stage-specific crop nutrition targets", "specialty crop fertilizers", ["MKP", "MAP", "DKP", "DAP", "TKPP"], ["soil, tissue and water analysis", "stage-specific nutrient delivery", "crop safety, yield and quality response"], ("Can one phosphate program fit an entire crop cycle?", "Not necessarily. Vegetative, flowering, fruiting and finishing stages can require different nitrogen, phosphorus and potassium contributions. Local agronomic advice and testing remain essential.")),
        ]),
]


PRODUCT_LINKS = {
    "STPP": "../products/food-ingredients/sodium-tripolyphosphate-stpp.html",
    "TKPP": "../products/food-ingredients/tetrapotassium-pyrophosphate-tkpp.html",
    "SHMP": "../products/food-ingredients/sodium-hexametaphosphate-shmp.html",
    "SALP": "../products/food-ingredients/sodium-aluminum-phosphate-salp.html",
    "MCP": "../products/food-ingredients/monocalcium-phosphate-mcp.html",
    "DCP": "../products/food-ingredients/dicalcium-phosphate-dcp.html",
    "CMC": "../products/food-ingredients/sodium-carboxymethyl-cellulose-cmc.html",
    "Calcium propionate": "../products/food-ingredients/calcium-propionate.html",
    "Citric acid": "../products/food-ingredients/citric-acid.html",
}

# Editorial angles are intentionally page-specific.  They describe the search
# decision behind each URL, not merely a synonym to be inserted into a shared
# paragraph.  This keeps the application cluster useful to engineers and
# buyers while giving search engines a clear, non-overlapping purpose for every
# page.
PAGE_ANGLES = {
    "meat-poultry-phosphate-systems": dict(
        primary="phosphates for meat and poultry processing",
        audience="processors troubleshooting purge, cook loss or an unstable meat emulsion",
        decision="whether water-binding phosphates, lactates, hydrocolloids, antioxidants or functional proteins address the measured loss mechanism",
        failure="High pickup is not the same as retained yield. Brine distribution, protein extraction, tumbling, thermal history and post-cook purge must be read together.",
        validation="Run a brine-control trial on the same raw-material lot; record pickup after equal drainage, cook loss, chilled purge, sliceability and sensory quality through shelf life.",
        heading="Build retained yield—not temporary pickup",
        faq=("What is the difference between STPP, TSPP and TKPP in processed meat?", "They differ in alkalinity, solubility and sequestration behavior. The useful choice depends on brine temperature, ionic strength, protein system, process time and local phosphate limits, so equal-dose substitution is not a reliable approval method.")),
    "seafood-phosphate-selection": dict(
        primary="phosphate treatment for shrimp and seafood processing",
        audience="shrimp, fish and shellfish processors managing thaw drip, glaze loss or soft texture",
        decision="how phosphate composition, water chemistry, soak conditions and non-phosphate supporting ingredients affect net retained quality",
        failure="Over-treatment can mask true yield, damage bite or create compliance risk; under-treatment may leave freeze–thaw loss and oxidation uncontrolled.",
        validation="Measure drained uptake, frozen weight, thaw drip, cook loss, texture, appearance and retained phosphate on representative seafood sizes and storage periods.",
        heading="Control freeze–thaw loss without sacrificing seafood texture",
        faq=("How should a seafood phosphate blend be compared?", "Compare blends at matched solution concentration, temperature, seafood-to-solution ratio, contact time and drainage. Judge net yield after thawing and cooking—not soak pickup alone.")),
    "bakery-leavening-phosphate-solutions": dict(
        primary="bakery leavening acids and mold inhibitor ingredients",
        audience="bakeries balancing gas-release timing, dough handling, crumb and mold-free shelf life",
        decision="which leavening acid, bicarbonate, emulsifier, hydrocolloid, mineral or preservative fits the product process",
        failure="A preservative that suppresses mold may also slow yeast, while the wrong leavening rate can shift bench tolerance, spread, volume and crumb color.",
        validation="Track dough or batter pH over time, specific volume, spread, crumb cell structure, firmness, flavor and challenged or real-time mold shelf life.",
        heading="Match leavening speed and preservation to the bakery process",
        faq=("Calcium propionate or potassium sorbate: which is better for bakery shelf life?", "Calcium propionate is widely screened in yeast-leavened bakery products; sorbate can be effective in suitable acidic products but may inhibit yeast. Product pH, application method, sensory limits and local permissions determine the trial design.")),
    "dairy-cheese-ingredient-solutions": dict(
        primary="processed cheese emulsifying salts and dairy stabilizers",
        audience="dairy formulators correcting oiling-off, weak body, syneresis or poor particle suspension",
        decision="how citrate and phosphate salt balance, calcium interaction and hydrocolloid choice control the target dairy structure",
        failure="The same emulsifying-salt blend can produce different melt and firmness when natural-cheese age, calcium, moisture, pH and shear change.",
        validation="Record cook pH, mixing torque, emulsion appearance, hot melt, cooled firmness, oil separation and syneresis across realistic storage temperatures.",
        heading="Design the mineral–protein interaction behind dairy texture",
        faq=("Why combine citrate and phosphate emulsifying salts in processed cheese?", "Citrates and phosphates provide different calcium-sequestering, buffering and creaming behavior. A ratio can be screened to reach the required melt and body, but it must be validated with the actual cheese blend and process.")),
    "beverage-formulation-ingredient-solutions": dict(
        primary="beverage stabilizer system for suspension and mouthfeel",
        audience="beverage developers diagnosing sediment, serum separation, ringing or unstable protein",
        decision="whether the instability originates from acid–protein interaction, insoluble particles, minerals, hydration, heat treatment or storage",
        failure="Adding more gum can increase viscosity without stopping sediment and can create ropiness, flavor release problems or difficult processing.",
        validation="Use a process-matched hydration order and measure pH, titratable acidity, Brix, viscosity, particle size, sediment height, ring formation and accelerated stability.",
        heading="Fix the instability mechanism before choosing a beverage gum",
        faq=("Gellan gum, CMC or pectin—which beverage stabilizer should be tested?", "Gellan is often screened for low-use suspension, CMC for body and protein protection in suitable systems, and pectin for selected acidified protein beverages. Calcium, pH, heat and desired mouthfeel decide the shortlist.")),
    "prepared-food-sauce-filling-solutions": dict(
        primary="sauce and filling stabilizer ingredients for freeze thaw stability",
        audience="prepared-food teams controlling cling, pumpability, emulsion breakdown and freeze–thaw water release",
        decision="how starch, xanthan, CMC, guar, alginate, emulsifier, protein and preservative functions should be layered",
        failure="A bench sample can look stable at rest yet fail during pumping, hot filling, retort, freezing or reheating because its shear and thermal history were not reproduced.",
        validation="Build flow curves at serving and process temperatures; test emulsion separation, freeze–thaw cycles, bake or reheat performance, pH, water activity and sensory shelf life.",
        heading="Engineer sauce texture through processing, storage and serving",
        faq=("How can a sauce stay thick after freezing and reheating?", "Select starch or gum systems against the actual shear, salt, acid and freeze–thaw cycle. Measure water release and viscosity after reheating; initial cold viscosity alone does not predict performance.")),

    "poultry-feed-phosphate-qualification": dict(primary="broiler and layer feed ingredients for amino acid and mineral balance", audience="feed mills and nutritionists qualifying ingredients for broiler, layer or breeder diets", decision="how digestible amino acids, available phosphorus, calcium, sodium and trace minerals fit the stage-specific matrix", failure="Total assay can hide differences in nutrient availability, impurity limits, particle size and phytase assumptions.", validation="Recalculate the complete diet, verify source documentation and mixing uniformity, then follow pellet quality, intake, performance and bone or egg-shell endpoints approved by the nutrition team.", heading="Qualify poultry ingredients by usable nutrient contribution", faq=("Should MCP and DCP be compared on total phosphorus price?", "No. Compare delivered cost per unit of approved available or digestible phosphorus together with calcium contribution, fluorine, heavy metals, physical quality and the phytase matrix used in the formula.")),
    "swine-feed-phosphate-selection": dict(primary="nursery pig feed acidifiers amino acids and phosphate sources", audience="swine nutrition and procurement teams working across nursery, grower-finisher and sow phases", decision="how digestible amino acids, mineral sources and organic acids change the complete diet rather than one specification line", failure="An acidifier response depends on basal-diet buffering, acid form, palatability and animal phase; published outcomes are not a guaranteed farm result.", validation="Review standardized digestible nutrient values, acid-binding capacity and feed handling, then use a controlled feeding plan with intake, gain, feed conversion and health observations.", heading="Formulate around the pig phase and the basal diet", faq=("When are fumaric and citric acid screened in pig feed?", "They are among the organic acids evaluated in nursery and other swine diets, but response varies with dose, basal ingredients and age. A qualified nutritionist must set the trial and legal use conditions.")),
    "ruminant-mineral-premix-phosphate-systems": dict(primary="dairy cattle mineral premix and rumen buffer ingredients", audience="dairy and beef teams closing mineral or buffer gaps identified in the full ration", decision="how forage, water, dry-matter intake and concentrate load change phosphate, salt, trace-mineral and buffer needs", failure="A generic premix can duplicate minerals already supplied by forage or water and may ignore antagonists, intake variation and stage of production.", validation="Use forage and water analyses, balance the total mixed ration, confirm premix uniformity and follow intake, rumen-related indicators and production measures selected by the nutritionist.", heading="Start with forage and water—not a standard mineral pack", faq=("Why is sodium bicarbonate used in some dairy rations?", "Bicarbonate is a physiological buffer and may be considered in high-concentrate or other suitable rations. Need and inclusion must be determined from the whole diet and approved by a ruminant nutritionist.")),
    "aquaculture-feed-ingredient-solutions": dict(primary="fish and shrimp feed amino acids and mineral ingredients", audience="aquafeed formulators balancing nutrient density, extrusion performance and water stability", decision="how species, life stage, feed habit and water exposure affect amino-acid and mineral-source value", failure="A soluble nutrient can meet the formula on paper yet leach from a slowly consumed pellet; a poorly sized mineral can weaken uniformity or extrusion behavior.", validation="Confirm formulation values and contaminants, then test mix uniformity, extrusion, pellet durability, float or sink behavior, water stability, nutrient leaching and controlled feeding outcomes.", heading="Protect nutrient delivery from the feed mill to the water", faq=("Why does water stability matter when selecting aquafeed ingredients?", "Fish and shrimp feeds remain in water before consumption. Ingredient solubility, binding and pellet structure can change nutrient leaching, so dry assay alone is not enough.")),
    "feed-premix-flow-trace-mineral-compatibility": dict(primary="feed premix ingredient compatibility flow and segregation", audience="premix and compound-feed plants investigating caking, demixing or nutrient loss", decision="how particle size, density, hygroscopicity and reactive mineral–vitamin contacts affect delivery", failure="A compliant incoming assay does not prevent segregation in conveying or reaction during humid storage.", validation="Map particle-size and bulk-density distributions, test mixing CV at multiple sampling points, simulate conveying and storage, and recheck sensitive nutrients at end of shelf life.", heading="Control the physical and chemical life of a feed premix", faq=("What causes segregation in a feed premix?", "Large differences in particle size, shape and density, vibration during handling and an unsuitable carrier can separate ingredients. Sampling after realistic transfer is more informative than mixer-exit data alone.")),

    "laundry-detergent-ingredient-solutions": dict(primary="laundry detergent raw materials for powder and liquid formulations", audience="detergent manufacturers balancing stain removal, hardness control, bleaching and product processing", decision="how surfactants, builders, alkalis, oxygen bleach and anti-redeposition aids share the cleaning task", failure="A stronger surfactant package cannot compensate for unmanaged hard water, poor bleach stability or soil redeposition.", validation="Use standard fabrics and target stains across relevant water hardness and wash temperatures; measure detergency, whiteness, redeposition, foam, powder flow or liquid stability.", heading="Build a laundry system around soil, water and product form", faq=("What roles do soda ash, sodium silicate and sodium percarbonate play in laundry powder?", "Soda ash contributes alkalinity and building, silicate can support alkalinity and processing or corrosion control, and percarbonate supplies oxygen bleach. Compatibility, moisture and storage stability must be tested in the complete powder.")),
    "hard-surface-cleaner-ingredient-solutions": dict(primary="hard surface cleaner ingredients for streak free cleaning", audience="formulators designing kitchen, bathroom, floor and multi-surface cleaners", decision="how wetting, solvent power, pH and residue affect the soil and named substrate", failure="Fast soil removal can still be unacceptable if the product streaks, dulls a coating or attacks stone, aluminum or seals.", validation="Test standardized soil on every claimed surface, including dwell and rinse conditions; score removal, wetting, streaking, gloss, corrosion and storage clarity.", heading="Match cleaning power to the surface claim", faq=("Can an acidic hard-surface cleaner be used on natural stone?", "Acid can attack carbonate-based stone. Each surface claim requires compatibility testing and clear use directions; a multi-surface position should never be inferred from one tile test.")),
    "industrial-degreaser-formulation-ingredients": dict(primary="industrial degreaser formulation ingredients for oil and grease", audience="plants selecting aqueous, solvent-assisted or alkaline degreasing systems", decision="whether soil chemistry and equipment favor solvency, emulsification, saponification or a combined route", failure="High alkalinity may remove fatty soil but can attack aluminum, coatings or seals; excess foam can disable spray equipment.", validation="Use aged representative oil on actual coupons and the intended spray, immersion or wipe method; measure removal, rinsability, foam, residue, corrosion and bath life.", heading="Choose the degreasing mechanism before the ingredient", faq=("When is a low-foam surfactant important in industrial degreasing?", "Spray cabinets and high-agitation systems can lose pressure or overflow when foam is excessive. Foam should be evaluated at operating temperature and soil load, not only in clean water.")),
    "acid-cleaner-descaler-ingredient-solutions": dict(primary="industrial descaling chemicals for calcium scale and rust deposits", audience="maintenance and formulation teams removing mineral deposits from compatible equipment", decision="which acid strength, chelation and wetting route dissolves the identified deposit without unacceptable substrate attack", failure="Limescale, iron oxide and mixed organic–mineral deposits do not respond identically, and chloride can be unacceptable for some metallurgy.", validation="Identify the deposit, weigh coupons, reproduce temperature and circulation, then measure dissolution, metal loss, gas evolution, spent-bath capacity and rinse endpoint.", heading="Identify the scale before selecting the acid", faq=("Citric acid or hydrochloric acid—which descaler is appropriate?", "Citric acid offers a different dissolution and compatibility profile from hydrochloric acid. Deposit composition, metallurgy, time, temperature, inhibitor package and waste route decide the safe candidate.")),
    "institutional-cleaning-hygiene-ingredients": dict(primary="institutional cleaning and disinfectant formulation ingredients", audience="commercial hygiene formulators separating routine soil removal from regulated antimicrobial claims", decision="how cleaning surfactants and a legally suitable active system fit the use site, organism claim and contact time", failure="An antimicrobial raw material does not make an untested formulation a registered disinfectant; soil can also reduce active performance.", validation="First verify cleaning, then test the finished product by the required efficacy method at label dilution and wet contact time, with stability and surface compatibility.", heading="Separate cleaning performance from disinfectant efficacy", faq=("Does benzalkonium chloride automatically make a cleaner a disinfectant?", "No. Active concentration, complete formula, efficacy data, use site, label and local registration determine any permitted sanitizing or disinfecting claim.")),
    "industrial-plant-cleaning-chemical-systems": dict(primary="industrial plant cleaning chemicals for CIP and equipment cleaning", audience="plant engineers planning alkaline, acid, oxidative or surfactant cleaning cycles", decision="how deposit sequence, metallurgy, circulation, temperature and wastewater limits define a cleaning program", failure="A single aggressive cycle can redistribute soil, damage gaskets or create a difficult effluent even when the visible deposit disappears.", validation="Map each deposit and material, establish pre-rinse and chemical stages, monitor concentration, temperature, flow and return condition, then verify rinse and cleanliness endpoints.", heading="Design the cleaning cycle around deposit sequence and equipment", faq=("What data are needed to select plant-cleaning chemicals?", "Provide deposit analysis, equipment materials, seals, volume, cleaning method, temperature, contact time, water quality, discharge route and the validated cleanliness endpoint.")),

    "raw-water-clarification-coagulant-solutions": dict(primary="raw water coagulant selection using jar testing", audience="water-treatment teams reducing turbidity and colloids ahead of filtration", decision="whether alum, ferric or polyaluminum chemistry fits raw-water pH, alkalinity, temperature and solids", failure="A dose optimized in one season can fail when temperature, natural organic matter or alkalinity changes.", validation="Use seasonally representative water in jar tests; record dose, rapid and slow mixing, floc appearance, settling, residual turbidity, pH, residual metal and sludge volume.", heading="Select coagulants from raw-water behavior, not habit", faq=("Why is a jar test needed for raw-water clarification?", "Coagulation depends on water chemistry and mixing. Jar testing compares dose and pH windows on the actual water before plant trials and helps expose sludge or residual-metal trade-offs.")),
    "industrial-wastewater-coagulant-selection": dict(primary="industrial wastewater coagulant selection for solids separation", audience="industrial sites treating variable emulsions, color, metals or suspended solids", decision="how contaminant form and downstream separation influence inorganic, organic or blended coagulant choice", failure="Reducing turbidity alone can move pollutants into a larger sludge volume or leave dissolved COD and metals untreated.", validation="Characterize composite samples, screen pH and dose, then measure settling or flotation, filtrate turbidity, target pollutants, sludge dewatering and downstream biological impact.", heading="Optimize the whole separation—not one turbidity number", faq=("PAC, ferric chloride or an organic coagulant—which should be tested?", "Their charge, pH demand, sludge and contaminant interactions differ. Use actual wastewater and the intended separator; no universal ranking applies.")),
    "cooling-water-biofouling-control-chemicals": dict(primary="cooling tower biocide chemicals for biofouling control", audience="cooling-water operators managing slime, heat-transfer loss and microbiological risk", decision="how oxidizing demand, metallurgy, pH, contact time and discharge limits shape a biocide program", failure="A measured feed concentration may be consumed before reaching remote surfaces, while uncontrolled dosing can accelerate corrosion or violate discharge conditions.", validation="Map system volume and demand, monitor residual at representative points, trend microbiological indicators, heat-transfer performance, corrosion and discharge compliance.", heading="Control the full cooling circuit—not only the dosing point", faq=("Oxidizing or non-oxidizing biocide for a cooling tower?", "The answer depends on system demand, biofilm, metallurgy, pH, residence time and regulations. Many programs use carefully controlled strategies rather than treating the options as interchangeable.")),
    "industrial-water-intake-biofouling-control": dict(primary="industrial water intake biofouling algae slime mussel control", audience="power, process and coastal facilities protecting intakes and water circuits", decision="how organism, life cycle, hydraulics and environmental permit define an intake treatment strategy", failure="A treatment that affects planktonic organisms may not remove established biofilm or mature macrofouling, and poorly timed dosing wastes chemical.", validation="Survey species and seasonal pressure, map concentration through the intake, verify exposure at critical points, and monitor settlement, pressure drop, corrosion and discharge.", heading="Time the treatment to the organism and intake hydraulics", faq=("Can the same chemistry control algae, slime and mussels?", "Not reliably. Target organism, growth stage, exposure and permit constraints differ. Site monitoring and specialist environmental review are required.")),
    "boiler-condensate-neutralizing-amine-solutions": dict(primary="boiler condensate neutralizing amine selection", audience="steam-system teams addressing low condensate pH and return-line corrosion", decision="how volatility and distribution ratio help place neutralizing capacity through the condensate network", failure="A single condensate sample can hide under-treated remote returns or overfeed near the boiler; amines do not correct every corrosion mechanism.", validation="Map sample points, trend pH, conductivity, iron and copper across operating loads, and confirm feed control, steam use restrictions and local requirements.", heading="Match amine distribution to the condensate network", faq=("How are morpholine and cyclohexylamine compared in condensate treatment?", "They distribute differently between steam and condensate. System pressure, return distance, metallurgy, steam end use and regulations determine whether one amine or a blend is evaluated.")),
    "process-water-reuse-chemical-solutions": dict(primary="industrial process water reuse treatment chemicals", audience="facilities conditioning wastewater for a defined reuse destination", decision="which coagulation, pH, oxidation or disinfection steps protect the downstream reuse process", failure="A clear effluent may still contain hardness, organics, microbes or residual chemistry that fouls membranes or disrupts production.", validation="Start with reuse-quality limits, perform mass balance and bench testing, then monitor the contaminants that govern the next unit operation and residuals introduced by treatment.", heading="Design backward from the water reuse specification", faq=("What does fit-for-purpose water reuse mean?", "Treatment targets are set by the intended use—such as cooling, washing or membrane feed—not by appearance alone. The receiving process and applicable rules define acceptance.")),

    "mine-water-treatment-chemical-solutions": dict(primary="mine water treatment chemicals for metals and suspended solids", audience="mine sites treating variable solids, acidity, dissolved metals and process-water returns", decision="how neutralization, precipitation, coagulation and flocculation should be sequenced for the actual water", failure="Raising pH can precipitate one metal while leaving another soluble and can create sludge that settles but dewaters poorly.", validation="Characterize dissolved and total metals, acidity and solids; run staged pH and reagent tests, then assess overflow quality, settling, sludge density and dewatering.", heading="Sequence metals precipitation and solids separation", faq=("Why is pH staging important in mine-water treatment?", "Different metal species have different precipitation behavior. Staged testing can identify a useful window while revealing reagent demand and sludge consequences.")),
    "mineral-leaching-chemical-solutions": dict(primary="mineral leaching reagents for pH and redox control", audience="metallurgical teams screening acids, alkalis and oxidants for a defined ore and extraction route", decision="how mineralogy, liberation, gangue consumption and redox behavior control reagent choice", failure="High extraction in a short bottle test can conceal excessive acid consumption, impurity dissolution or difficult downstream recovery.", validation="Use representative size fractions and mineralogy; track reagent consumption, pH or Eh, extraction kinetics, impurity loading, residue washability and downstream compatibility.", heading="Optimize extraction against reagent consumption and impurities", faq=("Can a leaching reagent be selected from ore grade alone?", "No. Mineral form, gangue, particle size, permeability, water chemistry and downstream recovery all affect the viable reagent and conditions.")),
    "mineral-flotation-reagent-solutions": dict(primary="mineral flotation reagents collectors frothers depressants modifiers", audience="concentrators improving grade, recovery or selectivity in a named ore system", decision="how collector, frother, depressant, activator and pH modifier interact with mineral surfaces and water chemistry", failure="More collector can increase recovery while sacrificing concentrate grade; froth stability can also carry entrained gangue rather than true flotation.", validation="Use representative grinding and water, vary one reagent factor at a time, and record kinetics, mass pull, grade, recovery, entrainment and froth character.", heading="Balance flotation recovery with selectivity and froth transport", faq=("Why test flotation reagents with site water?", "Dissolved ions, recycled reagents, hardness and pH can alter mineral surfaces and froth. Fresh laboratory water may give a misleading reagent ranking.")),
    "smelting-electrowinning-chemical-inputs": dict(primary="electrowinning electrolyte chemicals and metallurgical process inputs", audience="metallurgical operations controlling electrolyte condition, impurities and deposit quality", decision="how acidity, conductivity, redox and impurity control support the specific smelting or electrowinning circuit", failure="A bulk electrolyte assay may miss localized depletion, entrained organics or impurity species that roughen deposits and reduce current efficiency.", validation="Map solution composition and temperature through the circuit, trend voltage and current efficiency, inspect deposit morphology and close the impurity mass balance.", heading="Link electrolyte chemistry to metal deposit quality", faq=("What data are needed before supplying electrowinning chemicals?", "Identify the metal and circuit, electrolyte composition, impurity limits, operating temperature, current density, materials of construction and the deposit-quality problem.")),
    "mineral-refining-processing-chemicals": dict(primary="mineral refining and downstream processing chemicals", audience="refineries managing pH, crystallization, washing, dispersion or process-fluid stability", decision="which chemical function removes the actual downstream bottleneck without contaminating the final product", failure="A reagent that improves filtration may change crystal habit, leave a difficult residue or introduce an impurity outside product specification.", validation="Define the unit operation and product limit, then use mass-balanced trials covering yield, purity, filtration or settling, wash demand, recycle and residue quality.", heading="Protect final-product purity while improving the unit operation", faq=("How should a downstream mineral-processing aid be approved?", "Test both process improvement and its fate. Confirm where the reagent and its impurities report—to product, recycle, water or residue—before approval.")),

    "fertigation-phosphate-fertilizer-selection": dict(primary="MKP MAP fertilizer for fertigation and stock tank compatibility", audience="fertilizer blenders and growers selecting soluble phosphate for irrigation injection", decision="whether MKP, MAP or another phosphate matches the nitrogen-potassium plan, source water and stock-tank design", failure="A phosphate that dissolves in plain water can precipitate when concentrated with calcium or magnesium, blocking emitters.", validation="Analyze source water, calculate nutrient contribution, run concentrated stock and dilution compatibility tests, then monitor clarity, filter pressure and emitter uniformity.", heading="Choose fertigation phosphate by nutrient ratio and water compatibility", faq=("MKP or MAP for fertigation—which should be selected?", "MKP supplies phosphorus and potassium without nitrogen; MAP supplies phosphorus with ammonium nitrogen. Crop stage, total nutrient plan, water and stock-tank compatibility decide the choice.")),
    "foliar-phosphorus-potassium-solutions": dict(primary="foliar phosphorus potassium fertilizer using MKP", audience="specialty-fertilizer teams developing foliar phosphorus and potassium programs", decision="how nutrient need, salt load, spray-water quality and leaf sensitivity define a foliar candidate", failure="Complete dissolution does not guarantee leaf safety; concentration, temperature, humidity, adjuvants and tank partners can change burn risk.", validation="Confirm water quality and tank compatibility, then progress from small-area crop-safety tests to measured nutrient and crop-response trials under local agronomic supervision.", heading="Treat foliar nutrition as a spray-compatibility problem", faq=("Is water-soluble MKP automatically safe for foliar spraying?", "No. Solubility is only one factor. Crop, growth stage, concentration, spray conditions, water and tank partners must be evaluated locally for safety and response.")),
    "water-soluble-fertilizer-raw-material-qualification": dict(primary="water soluble fertilizer raw material qualification", audience="NPK and specialty-fertilizer manufacturers sourcing soluble nutrient salts", decision="how assay, insolubles, moisture, particle form and compatibility affect blend manufacture and field dissolution", failure="A high-assay material can still create sediment, caking or segregation that makes the finished blend inconsistent.", validation="Check identity and nutrients, insolubles, moisture and particle distribution; then make the real blend and test flow, caking, dissolution, solution clarity and storage.", heading="Qualify what happens after the raw material enters the blend", faq=("Which specifications matter for water-soluble fertilizer raw materials?", "Beyond nutrient assay, review water insolubles, moisture, pH, particle size, impurities, compatibility, caking behavior and destination-market requirements.")),
    "greenhouse-fertilizer-stock-tank-compatibility": dict(primary="hydroponic nutrient stock tank compatibility phosphate calcium", audience="greenhouse and soilless growers preventing concentrate precipitation and emitter blockage", decision="how water alkalinity and A/B tank separation keep calcium, phosphate and sulfate sources compatible", failure="Mixing concentrated calcium with phosphate or sulfate can form precipitates even when the final diluted recipe appears chemically reasonable.", validation="Analyze water, calculate concentrates, run timed stock and dilution tests, inspect sediment and filters, and verify delivered EC, pH and nutrients at representative emitters.", heading="Prevent precipitation before nutrients reach the root zone", faq=("Why are calcium and phosphate commonly separated in greenhouse stock tanks?", "At concentrate strength they can form sparingly soluble calcium phosphate. A/B separation and validated injection order reduce the risk, subject to the actual water and recipe.")),
    "compound-fertilizer-phosphate-raw-materials": dict(primary="MAP DAP phosphate raw materials for compound fertilizer production", audience="compound-fertilizer producers evaluating phosphate inputs for granulation and nutrient grade", decision="how MAP, DAP and related phosphates affect nutrient analysis, ammoniation, granulation, moisture and product hardness", failure="The same nominal nutrient grade can process differently because of free acid, moisture, particle size and impurities.", validation="Confirm nutrient and impurity specifications, then trial ammoniation or blending, granulation, drying and screening; measure recycle, granule strength, caking and finished analysis.", heading="Connect phosphate specification to granulation behavior", faq=("MAP or DAP for compound fertilizer production?", "They differ in nitrogen-to-phosphate contribution and process behavior. Target grade, ammoniation route, raw-material balance and granulation performance determine the selection.")),
    "specialty-crop-fertilizer-programs": dict(primary="specialty crop fertilizer program by growth stage", audience="horticulture and greenhouse teams building stage-specific nutrient programs", decision="how soil or substrate, tissue data, water and crop stage change the suitable phosphate source", failure="A calendar-based high-phosphorus program can ignore existing reserves, antagonism and the shift from vegetative growth to fruit quality.", validation="Set targets from soil, water and tissue information, use replicated local trials, and follow crop safety, nutrient status, yield, quality and residual conductivity.", heading="Build the nutrient program around crop stage and evidence", faq=("Should phosphorus stay constant through a specialty crop cycle?", "Not necessarily. Uptake, substrate reserves and the balance with nitrogen, potassium, calcium and micronutrients change. Local agronomic data should guide stage adjustments.")),
}


def esc(value): return html.escape(str(value), quote=True)


def display_heading(value):
    text = str(value).title()
    for old, new in (("Ph", "pH"), ("Rfq", "RFQ"), ("Brix", "Brix"),
                     ("Cod", "COD"), ("Cip", "CIP"), ("Coa", "COA"),
                     ("Tds", "TDS"), ("Sds", "SDS")):
        text = re.sub(rf"\b{old}\b", new, text)
    return text


def product_role(name, group):
    """Return an application-relevant role and a real approval question."""
    n = name.lower()
    rules = [
        (("stpp", "tspp", "tkpp", "shmp", "phosphate blend"), "phosphate functionality for water binding, buffering or sequestration", "Which blend composition, solution behavior and legal phosphate limit fit the actual process?"),
        (("mcp", "dcp", "map", "dap", "dkp", "tkp", "dsp"), "mineral or soluble nutrient source with a distinct counter-ion contribution", "What is the usable nutrient contribution, impurity profile, solubility and delivered cost in the complete system?"),
        (("methionine", "lysine", "threonine", "valine"), "crystalline amino acid for balancing digestible amino-acid supply", "Which assay basis, digestibility matrix, physical grade and animal-stage formula are being approved?"),
        (("carrageenan", "cmc", "xanthan", "guar", "gellan", "pectin", "alginate"), "hydrocolloid for water control, suspension, body or gel structure", "Does hydration order, ion level, shear and temperature produce the required texture without instability?"),
        (("starch", "distarch"), "modified starch for process viscosity and water management", "Does viscosity survive the real shear, heat, acid and freeze–thaw history?"),
        (("citrate", "citric acid", "gluconic", "lactic acid", "fumaric"), "organic acid or salt for pH, buffering, chelation or application-specific acidification", "What pH, buffering, compatibility, sensory or corrosion boundary applies to the finished system?"),
        (("hydrochloric", "phosphoric acid", "sulfuric", "caustic", "soda ash", "sodium silicate"), "acidic or alkaline process chemical for pH control, deposit removal or building", "What material compatibility, concentration, heat release, handling and waste limits govern use?"),
        (("labsa", "sles"), "primary surfactant raw material for wetting and soil removal", "How will it be neutralized or formulated, and what detergency, foam and rinse profile is required?"),
        (("alcohol", "propylene glycol", "glycerin"), "solvent, carrier or humectant with process-dependent behavior", "Are solvency, evaporation, flash point, residue, compatibility and regulatory status acceptable?"),
        (("percarbonate", "peroxide", "hypochlorite", "sdic", "tcca", "peracetic"), "oxidizing chemistry for bleaching, oxidation or a regulated antimicrobial system", "What active stability, contact condition, compatibility and finished-product claim data are required?"),
        (("benzalkonium",), "quaternary ammonium active for legally suitable antimicrobial formulations", "Does the complete product have the required efficacy data, label approval, contact time and surface compatibility?"),
        (("alum", "ferric", "polyaluminum", "pac", "coagulant"), "coagulant for charge neutralization and solids separation", "What dose and pH window gives acceptable residual water and manageable sludge in a jar test?"),
        (("amine", "morpholine", "cyclohexylamine"), "volatile alkalizing input for a designed steam-condensate program", "How does distribution through the real network affect remote pH, corrosion and steam-use compliance?"),
        (("collector", "xanthate"), "collector chemistry for selective mineral-surface hydrophobicity", "Which mineral, oxidation state, pH and site-water conditions define selectivity?"),
        (("frother", "mibc"), "frother for bubble and froth transport control", "Does the froth recover valuable mineral without excessive entrainment or downstream problems?"),
        (("depressant", "activator", "modifier"), "flotation modifier for mineral selectivity and pulp chemistry", "What mineral interaction and reagent sequence are demonstrated in representative ore?"),
        (("propionate", "sorbate", "benzoate", "diacetate"), "preservative candidate for a permitted food or feed application", "What pH, organism, sensory, process and destination-market use conditions must be validated?"),
        (("erythorbate", "ascorbic", "edta"), "antioxidant or chelating support for oxidation-sensitive systems", "Which oxidation marker, metal-ion environment and permitted-use limit define success?"),
        (("protein", "whey", "soy", "pea"), "functional or nutritional protein input", "Are composition, hydration, heat response, allergen status and sensory performance acceptable?"),
        (("sodium bicarbonate", "salt", "magnesium", "copper", "zinc", "manganese", "choline", "betaine"), "nutrient, buffer or functional feed input", "How does analyzed contribution fit the complete ration, authorization and premix compatibility?"),
    ]
    for needles, role, question in rules:
        if any(x in n for x in needles):
            return role, question
    return "candidate raw material with an application-specific functional role", "Which exact grade, assay, impurity limits, physical form and trial evidence support approval?"


def description(p):
    angle = PAGE_ANGLES[p["slug"]]
    text = f"Technical guide to {angle['primary']}: compare product roles, failure causes, validation metrics, compliance checks and RFQ data."
    return text if len(text) <= 175 else text[:171].rsplit(" ", 1)[0] + "."


def schema(group, p, desc):
    url=f"{BASE}/solutions/{p['slug']}.html"; q,a=p["faq"]
    angle=PAGE_ANGLES[p["slug"]]; q2,a2=angle["faq"]
    return {"@context":"https://schema.org","@graph":[
        {"@type":"WebPage","@id":url+"#webpage","url":url,"name":p["title"],"description":desc,"inLanguage":"en","dateModified":DATE,"about":{"@id":url+"#service"}},
        {"@type":"Service","@id":url+"#service","name":p["title"],"serviceType":"B2B ingredient and chemical application support","provider":{"@type":"Organization","name":"Bespring Chemical","url":BASE},"areaServed":"Worldwide","description":desc},
        {"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":BASE+"/"},{"@type":"ListItem","position":2,"name":group["hub_title"],"item":f"{BASE}/solutions/{group['hub']}"},{"@type":"ListItem","position":3,"name":p["title"],"item":url}]},
        {"@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}},{"@type":"Question","name":q2,"acceptedAnswer":{"@type":"Answer","text":a2}}]}
    ]}


def render(group, p):
    desc=description(p); canonical=f"{BASE}/solutions/{p['slug']}.html"; q,a=p["faq"]
    angle=PAGE_ANGLES[p["slug"]]; q2,a2=angle["faq"]
    title=p["title"] + (" | Ingredient Guide" if len(p["title"]) < 38 else "") + " | Bespring"
    product_rows="".join(
        f"<tr><th scope='row'>{esc(name)}</th><td>{esc(product_role(name,group)[0])}</td><td>{esc(product_role(name,group)[1])}</td></tr>"
        for name in p["products"])
    variable_notes=[
        f"Define this for {angle['audience']}; it determines whether the comparison reflects the real application.",
        f"Use measured values rather than assumptions. The central sourcing decision is {angle['decision']}.",
        f"Reproduce this condition during screening. {angle['failure']}",
        "Record mandatory legal, safety and customer limits before samples are requested; never infer permission from a product name.",
    ]
    variables="".join(f"<article class='sd-card'><span class='sd-card__index'>{i:02}</span><h3>{esc(display_heading(v))}</h3><p>{esc(variable_notes[i-1])}</p></article>" for i,v in enumerate(group["variables"],1))
    metric_notes=[
        f"Use this as the first diagnostic signal. Establish a baseline, then follow the relevant sequence: {angle['validation']}",
        f"Report this result for the control and each candidate under matched conditions. It must help decide {angle['decision']}.",
        f"Set a numerical or scored acceptance limit with {angle['audience']}; include variability, compliance and operating impact before scale-up.",
    ]
    metrics="".join(f"<article class='sd-metric'><h3>{esc(display_heading(m))}</h3><p>{esc(metric_notes[i])}</p></article>" for i,m in enumerate(p["metrics"]))
    product_links=[]
    for candidate in p["products"]:
        for key,url in PRODUCT_LINKS.items():
            if key.lower() in candidate.lower() and url not in {u for _,u in product_links}: product_links.append((candidate,url))
    related="".join(f"<a href='{url}'><span>Product detail</span><strong>{esc(name)}</strong><small>Review identity, specification and inquiry information.</small></a>" for name,url in product_links[:3])
    if not related: related=f"<a href='{group['catalog']}'><span>Product catalog</span><strong>Review available product grades</strong><small>Match identity and specification to the approved application.</small></a>"
    source_name,source_url=group["source"]
    return f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
<link rel="canonical" href="{canonical}"><link rel="alternate" hreflang="en" href="{canonical}"><link rel="alternate" hreflang="x-default" href="{canonical}">
<meta property="og:type" content="article"><meta property="og:site_name" content="Bespring Chemical"><meta property="og:title" content="{esc(p['title'])}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE}/images/{group['image']}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(p['title'])}"><meta name="twitter:description" content="{esc(desc)}">
<link rel="icon" href="../images/favicon.ico"><link rel="stylesheet" href="../css/style.css"><link rel="stylesheet" href="../css/site-pages.css"><link rel="stylesheet" href="../css/solution-detail.css"><link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
<script type="application/ld+json">{json.dumps(schema(group,p,desc),ensure_ascii=False,separators=(',',':'))}</script></head>
<body class="solution-detail application-solution-page"><div class="bs-seo-topbar"><div class="container bs-seo-topbar-container"><div class="bs-seo-topbar-left"><span class="bs-seo-highlight"><i class="fas fa-industry" aria-hidden="true"></i> China-based ingredient and chemical supplier</span><span class="bs-seo-divider">|</span><span>Exporting to 60+ countries</span></div><div class="bs-seo-topbar-right"><a href="mailto:info@bespringchem.com">info@bespringchem.com</a><a href="tel:+8613914896109">+86 139 1489 6109</a></div></div></div>
<header class="site-header"><div class="container nav-container"><div class="logo"><a href="../index.html"><img src="../images/logo.png" alt="Bespring Chemical"></a></div><nav class="main-nav" aria-label="Main navigation"><ul><li><a href="../index.html">Home</a></li><li><a href="../about/company-profile.html">About Us</a></li><li><a href="../products.html">Products</a></li><li><a href="../services.html">Services</a></li><li><a href="../news.html">News</a></li><li><a href="../contact.html" class="btn-nav">Contact</a></li></ul></nav><button class="hamburger" type="button" aria-label="Open navigation menu" aria-expanded="false"><i class="fas fa-bars"></i></button></div></header>
<main><section class="sd-hero" style="--sd-image:url('../images/{group['image']}')"><div class="sd-shell sd-hero__inner"><div class="sd-hero__content"><nav class="sd-breadcrumb" aria-label="Breadcrumb"><ol><li><a href="../index.html">Home</a></li><li><a href="{group['hub']}">{esc(group['hub_title'])}</a></li><li aria-current="page">{esc(p['title'])}</li></ol></nav><span class="sd-eyebrow">Application solution</span><h1>{esc(p['title'])}</h1><p class="sd-hero__lead">A selection, validation and procurement guide to {esc(p['focus'])}.</p><div class="sd-actions"><a class="sd-btn sd-btn--primary" href="#selection">Compare products</a><a class="sd-btn sd-btn--outline" href="#rfq">Prepare an RFQ</a></div></div></div></section>
<aside class="sd-trust"><div class="sd-shell sd-trust__grid"><div class="sd-trust__item"><strong>Problem first</strong><span>Define a measurable application target</span></div><div class="sd-trust__item"><strong>Broad screening</strong><span>Compare relevant product families</span></div><div class="sd-trust__item"><strong>Controlled evidence</strong><span>Baseline, candidate and pilot testing</span></div><div class="sd-trust__item"><strong>Specified supply</strong><span>Grade, COA, TDS, SDS and logistics</span></div></div></aside>
<section class="sd-section"><div class="sd-shell sd-intro"><div><span class="sd-eyebrow">Decision guide</span><h2>{esc(angle['heading'])}</h2></div><div class="sd-answer"><p><strong>For {esc(angle['primary'])}, the first question is {esc(angle['decision'])}.</strong></p><p>This guide is written for {esc(angle['audience'])}. The relevant shortlist spans {esc(', '.join(p['products'][:5]))}; each candidate has a different job, so they should not be presented as interchangeable alternatives.</p><p>{esc(angle['failure'])}</p><p><strong>Recommended evidence path:</strong> {esc(angle['validation'])}</p></div></div></section>
<nav class="sd-anchor-nav"><div class="sd-shell"><span>On this page</span><a href="#variables">Variables</a><a href="#selection">Product matrix</a><a href="#validation">Validation</a><a href="#metrics">Metrics</a><a href="#rfq">RFQ</a><a href="#faq">FAQ</a></div></nav>
<section class="sd-section sd-section--cream" id="variables"><div class="sd-shell"><header class="sd-section-head"><div><span class="sd-eyebrow">Application diagnosis</span><h2>Inputs that can change this specific decision</h2></div><p>These are not generic form fields: each must be fixed or measured before candidates for {esc(angle['primary'])} are ranked.</p></header><div class="sd-card-grid">{variables}</div></div></section>
<section class="sd-section" id="selection"><div class="sd-shell"><header class="sd-section-head"><div><span class="sd-eyebrow">Functional shortlist</span><h2>What each candidate contributes—and what must be challenged</h2></div><p>The table connects products to a functional hypothesis. It is a screening map, not a formula or an implied permission to use every listed material.</p></header><div class="sd-table-wrap"><table class="sd-table"><caption>Product functions and approval questions for {esc(angle['primary'])}</caption><thead><tr><th>Candidate</th><th>Reason to evaluate it</th><th>Question the trial must answer</th></tr></thead><tbody>{product_rows}</tbody></table></div><p class="sd-note"><strong>Approval boundary:</strong> Confirm the exact grade, specification, legal status, use conditions, labeling, worker safety and destination-market requirements before commercial use.</p></div></section>
<section class="sd-section sd-section--deep" id="validation"><div class="sd-shell"><header class="sd-section-head"><div><span class="sd-eyebrow">Application-specific approval</span><h2>Convert the technical hypothesis into repeatable evidence</h2></div><p>{esc(angle['validation'])}</p></header><div class="sd-process"><article><span>01</span><h3>Diagnose the mechanism</h3><p>{esc(angle['failure'])}</p></article><article><span>02</span><h3>Design the comparison</h3><p>Build the control around the real decision: {esc(angle['decision'])}. Hold unrelated raw-material and process variables constant.</p></article><article><span>03</span><h3>Challenge the result</h3><p>{esc(angle['validation'])} Repeat the leader at the realistic extremes that matter to {esc(angle['audience'])}.</p></article><article><span>04</span><h3>Freeze the approved grade</h3><p>Transfer the tested identity, critical limits, methods, documents, packing and change-control rules into purchasing; a different grade requires review.</p></article></div></div></section>
<section class="sd-section sd-section--cream" id="metrics"><div class="sd-shell"><header class="sd-section-head"><div><span class="sd-eyebrow">Evidence plan</span><h2>Measure the outcomes that decide approval</h2></div><p>Use defined sampling, controls and replication. Include technical performance, safety or compliance boundaries and total operating impact.</p></header><div class="sd-metric-grid">{metrics}</div></div></section>
<section class="sd-section" id="rfq"><div class="sd-shell"><header class="sd-section-head"><div><span class="sd-eyebrow">RFQ built for this application</span><h2>Ask suppliers questions that affect the trial</h2></div><p>For {esc(angle['primary'])}, a useful inquiry must explain the failure mechanism and intended evidence—not only request a price per tonne.</p></header><div class="sd-check-grid"><article class="sd-check"><h3>Current condition</h3><p>{esc(angle['failure'])} Provide the baseline values and representative sample information.</p></article><article class="sd-check"><h3>Decision and acceptance</h3><p>State {esc(angle['decision'])}, together with the test method, mandatory limit and desired improvement.</p></article><article class="sd-check"><h3>Exact supply controls</h3><p>Request identity, grade, assay, critical impurities, physical form, specification, recent COA, TDS, SDS and relevant declarations.</p></article><article class="sd-check"><h3>Trial and delivery</h3><p>Provide sample and pilot quantity, annual demand, packing, destination, Incoterm, delivery window and destination-market requirements.</p></article></div><p class="sd-review">Editorial review: Bespring Chemical technical and export team · Last reviewed {DATE}</p></div></section>
<section class="sd-section sd-section--cream" id="faq"><div class="sd-shell sd-faq"><div><span class="sd-eyebrow">Search questions answered</span><h2>Questions specific to {esc(angle['primary'])}</h2></div><div><details><summary>{esc(q)}</summary><p>{esc(a)}</p></details><details><summary>{esc(q2)}</summary><p>{esc(a2)}</p></details><details><summary>Can this page provide a final formula or dosage?</summary><p>No. It defines a technically relevant shortlist and evidence plan. Final use level and approval require the exact grade, actual process data, qualified technical review and applicable local rules.</p></details></div></div></section>
<section class="sd-section"><div class="sd-shell"><header class="sd-section-head"><div><span class="sd-eyebrow">Related resources</span><h2>Continue to the product portfolio</h2></div><p>Use product pages for identity and specification, and the industry page for the broader application map.</p></header><div class="sd-related"><a href="{group['hub']}"><span>Industry hub</span><strong>{esc(group['hub_title'])}</strong><small>Return to all supported application pathways.</small></a>{related}<a href="{group['catalog']}"><span>Product catalog</span><strong>Browse the complete related portfolio</strong><small>Review additional products and prepare a focused inquiry.</small></a></div><p class="sd-review"><strong>Technical reference:</strong> <a href="{source_url}" target="_blank" rel="noopener noreferrer">{esc(source_name)}</a></p></div></section>
<section class="sd-cta"><div class="sd-shell sd-cta__box"><div><span class="sd-eyebrow">Technical and commercial inquiry</span><h2>Share the data behind your application target.</h2><p>Include the process, current problem, target market, trial volume, annual demand and required documents.</p></div><a class="sd-btn sd-btn--primary" href="../contact.html">Prepare your RFQ <i class="fas fa-arrow-right"></i></a></div></section></main>
<footer class="crc-footer"><div class="container footer-grid"><div class="footer-col"><h3>Bespring Chemical</h3><p>Food, feed, cleaning, water-treatment, mining and agricultural raw-material solutions for international B2B supply.</p></div><div class="footer-col footer-links"><h3>Quick Links</h3><ul><li><a href="../products.html">Products</a></li><li><a href="{group['hub']}">Solutions</a></li><li><a href="../services.html">Services</a></li><li><a href="../news.html">Knowledge Center</a></li></ul></div><div class="footer-col"><h3>Contact</h3><p><a href="mailto:info@bespringchem.com">info@bespringchem.com</a></p><a href="../contact.html" class="contact-btn-footer">Request information</a></div></div><div class="footer-bottom">&copy; 2026 Bespring Chemical Co., Ltd.</div></footer><script>const h=document.querySelector('.hamburger'),n=document.querySelector('.main-nav');h?.addEventListener('click',()=>{{const o=n.classList.toggle('active');h.setAttribute('aria-expanded',String(o))}});</script></body></html>'''


def update_hub(group):
    path=ROOT/"solutions"/group["hub"]
    raw=path.read_bytes(); bom=raw.startswith(b"\xef\xbb\xbf"); text=raw.decode("utf-8-sig")
    # Remove the earlier standalone phase-one link block; application cards now carry the links.
    text=re.sub(r"\s*<!-- PHASE-ONE-SOLUTION-CLUSTER-START -->.*?<!-- PHASE-ONE-SOLUTION-CLUSTER-END -->", "", text, flags=re.S)
    text=re.sub(r"\s*<section class=\"solution-cluster\"[^>]*aria-labelledby=\"phase-one-solutions-title\".*?</section>", "", text, flags=re.S)
    grid_pattern=rf'(<div class="{re.escape(group["grid_class"])}">)(.*?)(</div>)'
    match=re.search(grid_pattern,text,flags=re.S)
    if not match: raise RuntimeError(f"application grid not found: {group['hub']}")
    body=match.group(2); pages=group["pages"]
    opening=rf'<article class="{re.escape(group["card_class"])}">'
    found=len(re.findall(opening,body))
    linked=len(re.findall(rf'<a class="{re.escape(group["card_class"])}"\s+href="[^"]+\.html"',body))
    if found == 0 and linked == len(pages):
        # Hubs may already be wired from a previous build.  Keep the operation
        # idempotent so content-only rebuilds do not fail or duplicate links.
        output=text.encode("utf-8")
        path.write_bytes((b"\xef\xbb\xbf" if bom else b"")+output)
        return
    if found != len(pages): raise RuntimeError(f"{group['hub']}: expected {len(pages)} cards, found {found}")
    index=0
    def open_link(_):
        nonlocal index
        href=pages[index]["slug"]+".html"; index+=1
        return f'<a class="{group["card_class"]}" href="{href}" aria-label="Read {esc(pages[index-1]["title"])}">'
    body=re.sub(opening,open_link,body)
    body=body.replace("</article>","</a>")
    text=text[:match.start()]+match.group(1)+body+match.group(3)+text[match.end():]
    output=text.encode("utf-8")
    path.write_bytes((b"\xef\xbb\xbf" if bom else b"")+output)


def remove_obsolete(target_slugs):
    removed=[]
    for path in (ROOT/"solutions").glob("*.html"):
        slug=path.stem
        if slug in target_slugs: continue
        text=path.read_text(encoding="utf-8-sig")
        if "solution-cluster-page" in text or slug in {"feed-phosphate-mcp-dcp-selection","mkp-vs-map-fertilizer-solutions"}:
            path.unlink(); removed.append(slug)
    return removed


def rebuild_sitemap():
    path=ROOT/"sitemap.xml"; ns="http://www.sitemaps.org/schemas/sitemap/0.9"; q="{"+ns+"}"
    ET.register_namespace("",ns)
    old={}
    if path.exists():
        tree=ET.parse(path)
        for node in tree.getroot().findall(q+"url"):
            loc=node.findtext(q+"loc")
            if loc: old[loc]=node
    urls=[]
    for file in ROOT.rglob("*.html"):
        rel=file.relative_to(ROOT).as_posix()
        urls.append(f"{BASE}/{rel}" if rel != "index.html" else BASE+"/")
    root=ET.Element(q+"urlset")
    for url in sorted(set(urls)):
        if url in old: root.append(old[url]); continue
        node=ET.SubElement(root,q+"url"); ET.SubElement(node,q+"loc").text=url
        ET.SubElement(node,q+"lastmod").text=DATE; ET.SubElement(node,q+"changefreq").text="monthly"; ET.SubElement(node,q+"priority").text="0.7"
    tree=ET.ElementTree(root); ET.indent(tree,space="  "); tree.write(path,encoding="utf-8",xml_declaration=True)


def main():
    pages=[(g,p) for g in GROUPS for p in g["pages"]]
    target={p["slug"] for _,p in pages}
    removed=remove_obsolete(target)
    for group,p in pages:
        (ROOT/"solutions"/f"{p['slug']}.html").write_text(render(group,p),encoding="utf-8")
    for group in GROUPS: update_hub(group)
    rebuild_sitemap()
    print(f"Built {len(pages)} application pages; removed {len(removed)} obsolete solution pages; updated 6 hubs and sitemap")
    if removed: print("Removed:",", ".join(sorted(removed)))


if __name__ == "__main__": main()
